kind: Namespace
apiVersion: v1
metadata:
  name: dev

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: static-app
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-app
  template:
    metadata:
      labels:
        app: static-app
    spec:
      containers:
      - name: besant-app
        image: <docker-image>
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: static-service
  namespace: dev
spec:
  selector:
    app: static-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001



